import type { Metadata } from "next";
import "./globals.css";
import { Inter, Calistoga } from "next/font/google";
import Sidebar from "./components/Sidebar";
import Footter from "./components/Footter";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const calistoga = Calistoga({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${calistoga.variable} antialiased bg-gray-900 text-white font-sans relative`}
      >
        <div className="fixed bottom-0 lg:right-10 lg:top-1/2 lg:transform lg:-translate-y-1/2 max-lg:w-full">
          <Sidebar />
        </div>
        {children}
        <Footter/>
      </body>
    </html>
  );
}
